# Programming Project 3

**Author:** Molly Rovinski

**Version:** 1.0

**Semester:** Fall 2020

**Problem A:** Write a function that will accept the filename of data about African country population for 5 years and return the dataset as a list. 

In [2]:
import csv

def readfile(filename):
    """This function reads a file and prints it into a list. It also replaces the \n at the end of all the lists with a blank. Because csv assumes that every comma is a separate element, the countries with commas in their names caused the length of each row to need to be taken into account to be corrected for output."""
    ans = []
    with open (filename, mode = 'r') as file:
        for rec in file:
            l = rec.replace('\n','').split(',')
            if len(l) > 7:
                l = [l[0] + ',' + l[1]] + l[2:]
            ans.append(l)
    return ans

data = readfile('africa_pop_data.csv')
print(data)

[['Country', 'Code', '2015', '2016', '2017', '2018', '2019'], ['Algeria', 'DZA', '39728025', '40551404', '41389198', '42228429', '43053054'], ['Angola', 'AGO', '27884381', '28842484', '29816748', '30809762', '31825295'], ['Benin', 'BEN', '10575952', '10872067', '11175204', '11485048', '11801151'], ['Botswana', 'BWA', '2120716', '2159944', '2205128', '2254126', '2303697'], ['Burkina Faso', 'BFA', '18110624', '18646378', '19193284', '19751535', '20321378'], ['Cabo Verde', 'CPV', '524743', '531146', '537497', '543767', '549935'], ['Cameroon', 'CMR', '23298368', '23926539', '24566045', '25216237', '25876380'], ['Central African Republic', 'CAF', '4493170', '4537687', '4596028', '4666377', '4745185'], ['Chad', 'TCD', '14110975', '14561666', '15016773', '15477751', '15946876'], ['Comoros', 'COM', '777424', '795592', '813892', '832322', '850886'], ['"Congo, Dem. Rep."', 'COD', '76244544', '78789127', '81398764', '84068091', '86790567'], ['"Congo, Rep."', 'COG', '4856095', '4980999', '5110702'

**Problem B:** Write a function that will accept a dataset (list) that contains the African country populations that will return a NumPy array with only the numerical data. 

In [3]:
import numpy as np

In [4]:
def pop_array(setlist):
    """This function takes the data from a list and puts it into a NumPy Array. With the length of each countries data being different, it had to call the last 5 elements for consistency. So it takes each sublist within the main list except the first one and uses the last five elements to make each row in the Array. """
    arr = [sub[-5:] for sub in setlist[1:]]
    for x in range(len(arr)):
        for i in range(len(arr[x])):
            arr[x][i] = int(arr[x][i])
    return np.array(arr)
nparr = pop_array(data)
print(nparr)

[[ 39728025  40551404  41389198  42228429  43053054]
 [ 27884381  28842484  29816748  30809762  31825295]
 [ 10575952  10872067  11175204  11485048  11801151]
 [  2120716   2159944   2205128   2254126   2303697]
 [ 18110624  18646378  19193284  19751535  20321378]
 [   524743    531146    537497    543767    549935]
 [ 23298368  23926539  24566045  25216237  25876380]
 [  4493170   4537687   4596028   4666377   4745185]
 [ 14110975  14561666  15016773  15477751  15946876]
 [   777424    795592    813892    832322    850886]
 [ 76244544  78789127  81398764  84068091  86790567]
 [  4856095   4980999   5110702   5244363   5380508]
 [ 23226143  23822714  24437469  25069229  25716544]
 [   913993    929112    944097    958920    973560]
 [ 92442547  94447072  96442593  98423595 100388073]
 [  1168568   1215179   1262001   1308974   1355986]
 [  1104044   1113984   1124753   1136191   1148130]
 [100835458 103603501 106400024 109224559 112078730]
 [  1947686   2007873   2064823   2119275   21

**Problem C:** Write a function that will accept a data list that contains the African country populations that will return PrettyTable of the data. 

In [5]:
from prettytable import PrettyTable    

In [6]:
def pop_pt(datas):
    """This function creates a PrettyTable of the Data from the data list. It makes the elements in the sublist 0 and makes it the headers. Then it takes all the data in sublist 1 through the end and inputs the data in each row."""
    pt = PrettyTable()
    pt.field_names = datas[0]
    for row in datas[1:]:
        pt.add_row(row)
    print (pt)
pop_pt(data)

+--------------------------+------+-----------+-----------+-----------+-----------+-----------+
|         Country          | Code |    2015   |    2016   |    2017   |    2018   |    2019   |
+--------------------------+------+-----------+-----------+-----------+-----------+-----------+
|         Algeria          | DZA  |  39728025 |  40551404 |  41389198 |  42228429 |  43053054 |
|          Angola          | AGO  |  27884381 |  28842484 |  29816748 |  30809762 |  31825295 |
|          Benin           | BEN  |  10575952 |  10872067 |  11175204 |  11485048 |  11801151 |
|         Botswana         | BWA  |  2120716  |  2159944  |  2205128  |  2254126  |  2303697  |
|       Burkina Faso       | BFA  |  18110624 |  18646378 |  19193284 |  19751535 |  20321378 |
|        Cabo Verde        | CPV  |   524743  |   531146  |   537497  |   543767  |   549935  |
|         Cameroon         | CMR  |  23298368 |  23926539 |  24566045 |  25216237 |  25876380 |
| Central African Republic | CAF  |  449

**Problem D:** Write a function that will accept the NumPy array that contains the population data for the African countries and that prints a summary table of statistics for each year.

In [7]:
def helper(vals):
    """This function formats the numbers in the arrays to have two decimal places and commas. It takes every three digits in an element and places a comma in between them and then appends each three digit section together. It also cuts off the last two digits of the numbers at the end of the number and then appends them after a decimal place at the end (which serves a purpose in the following function when each mean, max, and min is multiplied by 100)."""
    res = []
    for val in vals:
        num = int((len(str(int(val)))-3)/3)
        ans = ''
        for i in range(num):
            ans = ',' + val[len(val)-3-3*i - 2:len(val)-3*i - 2] + ans
        ans = val[:len(val) - 3*num - 2] + ans + '.' + val[-2:]
        res.append(ans)
    return res

def pop_stat(data):
    """This function creates a pretty table for the summary output. It prints a title for the chart and each row with the mean, min, and max for each year. It multiplies each mean, min, and max by 100 and then converts them to integers to preserve the first two digits of the decimal as was mentioned in the previous function."""
    pt = PrettyTable()
    print ("African Population Statistics")
    pt.field_names = ['Summary Measure','2015', '2016', '2017', '2018', '2019']
    
    mean = np.mean(data, axis=0) * 100
    maxi = np.max(data, axis=0) * 100
    mini = np.min(data, axis=0) * 100
    means = []
    maxes = []
    mins = []
    for i in range(len(mean)):
        means.append(str(int(mean[i])))
        maxes.append(str(maxi[i]))
        mins.append(str(mini[i]))
    
    row = helper(means)
    pt.add_row(['mean'] + row)
    row = helper(maxes)
    pt.add_row(['max'] + row)
    row = helper(mins)
    pt.add_row(['min'] + row)
     
    pt.align = "r"
    print(pt)
pop_stat(nparr)

African Population Statistics
+-----------------+----------------+----------------+----------------+----------------+----------------+
| Summary Measure |           2015 |           2016 |           2017 |           2018 |           2019 |
+-----------------+----------------+----------------+----------------+----------------+----------------+
|            mean |  22,491,651.21 |  23,072,804.01 |  23,664,411.28 |  24,265,356.30 |  24,874,643.13 |
|             max | 181,137,448.00 | 185,960,289.00 | 190,873,311.00 | 195,874,740.00 | 200,963,599.00 |
|             min |      93,419.00 |      94,677.00 |      95,843.00 |      96,762.00 |      97,625.00 |
+-----------------+----------------+----------------+----------------+----------------+----------------+


**Problem E:** Write a code that calls the functions to get the data froma file and extract the data to an array and print it in a table. 

In [8]:
data = readfile('africa_pop_data.csv')
print(data)

print(nparr)

pop_pt(data)

pop_stat(nparr)

[['Country', 'Code', '2015', '2016', '2017', '2018', '2019'], ['Algeria', 'DZA', '39728025', '40551404', '41389198', '42228429', '43053054'], ['Angola', 'AGO', '27884381', '28842484', '29816748', '30809762', '31825295'], ['Benin', 'BEN', '10575952', '10872067', '11175204', '11485048', '11801151'], ['Botswana', 'BWA', '2120716', '2159944', '2205128', '2254126', '2303697'], ['Burkina Faso', 'BFA', '18110624', '18646378', '19193284', '19751535', '20321378'], ['Cabo Verde', 'CPV', '524743', '531146', '537497', '543767', '549935'], ['Cameroon', 'CMR', '23298368', '23926539', '24566045', '25216237', '25876380'], ['Central African Republic', 'CAF', '4493170', '4537687', '4596028', '4666377', '4745185'], ['Chad', 'TCD', '14110975', '14561666', '15016773', '15477751', '15946876'], ['Comoros', 'COM', '777424', '795592', '813892', '832322', '850886'], ['"Congo, Dem. Rep."', 'COD', '76244544', '78789127', '81398764', '84068091', '86790567'], ['"Congo, Rep."', 'COG', '4856095', '4980999', '5110702'